@echo off
setlocal DisableDelayedExpansion
chcp 65001 >nul
set "TOOLBAR_ROOT=%~dp0.."
set "TOOLBAR_ACTION=%~1"
echo Codex++ Usage Toolbar
echo Preparing local runtime. First download may take a few minutes.
rem Run a built-in PowerShell command, not a .ps1 file; no execution policy changes.
rem Node downloads use a pinned version and SHA-256 from nodejs.org.
powershell.exe -NoLogo -NoProfile -Command "$ErrorActionPreference='Stop'; try { if (@('install','diagnose','uninstall','rollback','repair','update') -notcontains $env:TOOLBAR_ACTION) { throw 'Unsupported action' }; $node=$null; $candidate=Get-Command node.exe -ErrorAction SilentlyContinue; if ($candidate) { try { $v= & $candidate.Source -p 'process.versions.node'; $parts=$v.Split('.'); $major=[int]$parts[0]; $minor=[int]$parts[1]; if ($LASTEXITCODE -eq 0 -and ($major -ge 26 -or ($major -eq 25 -and $minor -ge 4) -or ($major -eq 24 -and $minor -ge 14))) { $node=$candidate.Source } } catch {} }; if (-not $node) { $arch=if ($env:PROCESSOR_ARCHITECTURE -eq 'ARM64' -or $env:PROCESSOR_ARCHITEW6432 -eq 'ARM64') {'arm64'} else {'x64'}; $expected=if ($arch -eq 'arm64') {'3958e4bb3f2d4ef37c938215dfc65a9d3c9d839b5060fec103bd2345fa78e951'} else {'3602f2bb1a10f2cbab4c36886218a33c1ab3db87290e73b033c46c77147d0237'}; $dir=Join-Path $env:LOCALAPPDATA ('CodexUsageToolbar\runtime\v24.19.0-win-'+$arch); [IO.Directory]::CreateDirectory($dir) | Out-Null; $node=Join-Path $dir 'node.exe'; if (-not (Test-Path -LiteralPath $node)) { $temporary=Join-Path $dir ([guid]::NewGuid().ToString()+'.tmp'); try { [Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12; Invoke-WebRequest -UseBasicParsing -MaximumRedirection 0 -Uri ('https://nodejs.org/download/release/v24.19.0/win-'+$arch+'/node.exe') -OutFile $temporary; if ((Get-FileHash -LiteralPath $temporary -Algorithm SHA256).Hash -ne $expected) { throw 'Node checksum mismatch. Download was not executed.' }; Move-Item -LiteralPath $temporary -Destination $node } finally { if (Test-Path -LiteralPath $temporary) { Remove-Item -LiteralPath $temporary } } }; if ((Get-FileHash -LiteralPath $node -Algorithm SHA256).Hash -ne $expected) { throw 'Cached Node checksum mismatch.' } }; Remove-Item Env:NODE_OPTIONS -ErrorAction SilentlyContinue; $extra=@(); if ($env:TOOLBAR_DATA_ROOT) { $extra=@('--data-root',$env:TOOLBAR_DATA_ROOT) }; & $node (Join-Path $env:TOOLBAR_ROOT 'scripts\manage.mjs') $env:TOOLBAR_ACTION @extra; exit $LASTEXITCODE } catch { Write-Host ('FAILED: '+$_.Exception.Message) -ForegroundColor Red; exit 1 }"
set "TOOLBAR_RESULT=%errorlevel%"
if not "%TOOLBAR_RESULT%"=="0" echo Operation failed. Read the message above. For network errors, retry later or install Node.js 24.19.0 from https://nodejs.org
if not "%TOOLBAR_NO_PAUSE%"=="1" pause
exit /b %TOOLBAR_RESULT%
